// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulseRisk.Infrastructure.Persistence;

#nullable disable

namespace PulseRisk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulseRiskDbContext))]
    [Migration("20260701150235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PulseRisk.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.Instrument", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_asset");

                    b.Property<decimal>("ContractSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("contract_size");

                    b.Property<int>("Digits")
                        .HasColumnType("integer")
                        .HasColumnName("digits");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quote_asset");

                    b.HasKey("Symbol")
                        .HasName("pk_instruments");

                    b.ToTable("instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Symbol = "EURUSD",
                            BaseAsset = "EUR",
                            ContractSize = 100000m,
                            Digits = 5,
                            IsActive = true,
                            QuoteAsset = "USD"
                        },
                        new
                        {
                            Symbol = "GBPUSD",
                            BaseAsset = "GBP",
                            ContractSize = 100000m,
                            Digits = 5,
                            IsActive = true,
                            QuoteAsset = "USD"
                        },
                        new
                        {
                            Symbol = "XAUUSD",
                            BaseAsset = "XAU",
                            ContractSize = 100m,
                            Digits = 2,
                            IsActive = true,
                            QuoteAsset = "USD"
                        });
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("average_price");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<decimal>("FloatingPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("floating_pn_l");

                    b.Property<decimal>("NetVolume")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("net_volume");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("trading_account_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("ix_positions_symbol");

                    b.HasIndex("ClientId", "Symbol")
                        .HasDatabaseName("ix_positions_client_id_symbol");

                    b.HasIndex("TradingAccountId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_positions_trading_account_id_symbol");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Ask")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("ask");

                    b.Property<decimal>("Bid")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("bid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("Symbol", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_quotes_symbol_timestamp");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.RiskAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("alert_type");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("trading_account_id");

                    b.HasKey("Id")
                        .HasName("pk_risk_alerts");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("ix_risk_alerts_resolved_at");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("ix_risk_alerts_symbol");

                    b.HasIndex("TradingAccountId")
                        .HasDatabaseName("ix_risk_alerts_trading_account_id");

                    b.HasIndex("ClientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_risk_alerts_client_id_created_at");

                    b.HasIndex("Severity", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_risk_alerts_severity_created_at");

                    b.HasIndex("ClientId", "TradingAccountId", "Symbol", "AlertType")
                        .HasDatabaseName("ix_risk_alerts_client_id_trading_account_id_symbol_alert_type")
                        .HasFilter("resolved_at IS NULL");

                    b.ToTable("risk_alerts", (string)null);
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.RiskRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<decimal>("ThresholdValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("threshold_value");

                    b.HasKey("Id")
                        .HasName("pk_risk_rules");

                    b.HasIndex("RuleType", "IsEnabled")
                        .HasDatabaseName("ix_risk_rules_rule_type_is_enabled");

                    b.ToTable("risk_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsEnabled = true,
                            Name = "Max exposure limit",
                            RuleType = "MaxExposureLimit",
                            Severity = "Critical",
                            ThresholdValue = 1000000m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsEnabled = true,
                            Name = "Max loss limit",
                            RuleType = "MaxLossLimit",
                            Severity = "Critical",
                            ThresholdValue = -25000m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsEnabled = true,
                            Name = "Margin level warning",
                            RuleType = "MarginLevelWarning",
                            Severity = "Warning",
                            ThresholdValue = 100m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsEnabled = true,
                            Name = "Price spike detection",
                            RuleType = "PriceSpikeDetection",
                            Severity = "Warning",
                            ThresholdValue = 2.5m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsEnabled = true,
                            Name = "High frequency trading activity",
                            RuleType = "HighFrequencyTradingActivity",
                            Severity = "Warning",
                            ThresholdValue = 100m
                        });
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("open_price");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("side");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("trading_account_id");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("ClientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trades_client_id_created_at");

                    b.HasIndex("Symbol", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trades_symbol_created_at");

                    b.HasIndex("TradingAccountId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trades_trading_account_id_created_at");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.TradingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("leverage");

                    b.HasKey("Id")
                        .HasName("pk_trading_accounts");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_trading_accounts_client_id");

                    b.ToTable("trading_accounts", (string)null);
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.Position", b =>
                {
                    b.HasOne("PulseRisk.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_clients_client_id");

                    b.HasOne("PulseRisk.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_instruments_symbol");

                    b.HasOne("PulseRisk.Domain.Entities.TradingAccount", null)
                        .WithMany()
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_trading_accounts_trading_account_id");
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.Quote", b =>
                {
                    b.HasOne("PulseRisk.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_instruments_symbol");
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.RiskAlert", b =>
                {
                    b.HasOne("PulseRisk.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_alerts_clients_client_id");

                    b.HasOne("PulseRisk.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_alerts_instruments_symbol");

                    b.HasOne("PulseRisk.Domain.Entities.TradingAccount", null)
                        .WithMany()
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_alerts_trading_accounts_trading_account_id");
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.Trade", b =>
                {
                    b.HasOne("PulseRisk.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trades_clients_client_id");

                    b.HasOne("PulseRisk.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trades_instruments_symbol");

                    b.HasOne("PulseRisk.Domain.Entities.TradingAccount", null)
                        .WithMany()
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trades_trading_accounts_trading_account_id");
                });

            modelBuilder.Entity("PulseRisk.Domain.Entities.TradingAccount", b =>
                {
                    b.HasOne("PulseRisk.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trading_accounts_clients_client_id");
                });
#pragma warning restore 612, 618
        }
    }
}
